on: push
name: New workflow
jobs:
  konstruktoidShellCheck:
    name: Konstruktoid ShellCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Konstruktoid ShellCheck
      uses: ./action-shellcheck
